language: objective-c
osx_image: xcode7.3
script:
- xctool test -project FontKit.xcodeproj -scheme FontKit -sdk iphonesimulator
  ONLY_ACTIVE_ARCH=NO
before_deploy:
  - carthage build --no-skip-current
  - carthage archive FontKit
deploy:
  provider: releases
  api_key:
    secure: cas9AI0zCDIumfTKk79sazU6PLuVXICET6eIjqivntG1Qs1g9yvmsI3JbBMLPyZqDl0w+uDHhki7cBeO3tDXJ8cxIErj8xYwtX4TMnA916QWqo7DVkGjkqAxosWWBGBgx6VbcSw0WSnPYrlo41c5yKssuDal+CZjoTeadJqB8Rg=
  file: FontKit.framework.zip
  skip_cleanup: true
  on:
    tags: true
    repo: YevheniiPylypenko/FontKit
